name: etf-comparator
version: 0.1.0.0
# license:
# author:
# maintainer:
description: ETF composition comparison tool


default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - RecordWildCards

dependencies:
  - base >= 4.14 && < 5
  - containers
  - text
  - bytestring
  - vector
  - cassava
  - filepath
  - directory
  - mtl
  - yaml
  - time
  - aeson
  - xlsx
  - lens

library:
  source-dirs: [src, app]
  exposed-modules:
    - Domain.Comparison
    - Domain.Errors
    - Domain.Merge
    - Domain.Normalization
    - Domain.Types
    - Domain.Validation
    - Ingestion.AssetIdMapping
    - Ingestion.FileLoader
    - Ingestion.FileMeta
    - Ingestion.MappingLoader
    - Ingestion.ResolveAssetId
    - Ingestion.Router
    - Ingestion.TableLoader
    - Ingestion.UnsolvedId
    - Ingestion.Xlsx
    - Parser.Common.ParserHelpers
    - Parser.Common.PreprocessHelpers
    - Parser.Custom
    - Parser.IShares
    - Parser.Preprocess.Custom
    - Parser.Preprocess.IShares
    - Parser.Preprocess.StateStreet
    - Parser.StateStreet
    - Service.Config
    - Service.OutputWriter
    - Service.Pipeline

tests:
  etf-comparator-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - etf-comparator
      - hspec
    other-modules:
      - DemoComparison
      - Domain.ComparisonSpec
      - Domain.MergeSpec
      - Domain.NormalizationSpec
      - Domain.ValidationSpec
      - Ingestion.FileLoaderSpec
      - Ingestion.FileMetaSpec
      - Ingestion.MappingLoaderSpec
      - Ingestion.ResolveAssetIdSpec
      - Parser.CustomSpec
      - Parser.ISharesSpec
      - Parser.StateStreetSpec
      - Service.OutputWriterSpec
      - Service.PipelineSpec

executables:
  etf-comparator:
    main: Service/Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Service.Main
    dependencies:
      - etf-comparator

  reconcile:
    main: Service/Reconcile.hs
    source-dirs: app
    ghc-options:
      - -main-is Service.Reconcile
    dependencies:
      - etf-comparator
      - base
      - bytestring
      - cassava
      - containers
      - directory
      - filepath
      - text
      - vector
